language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
script:
  - bundle exec rspec

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    - jwaterfaucett@gmail.com